on:
  release:
    types: [created]

env:
  PYTHON_VERSION: '3.12'
  XCODE_VERSION: '16.1'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-15-intel
            platform: darwin
            arch: x64
          - os: macos-15
            platform: darwin
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: '24.x'

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Set up Xcode ${{ env.XCODE_VERSION }}
        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app

      - name: Environment Information
        run: npx envinfo

      - name: Build Qode binary
        run: node ./qode/build.js
        env:
          TARGET_ARCH: ${{ matrix.arch }}

      - name: Compress files
        uses: a7ul/tar-action@v1.0.2
        with:
          command: c
          cwd: ./out/Release
          files: |
            ./qode
          outPath: ${{github.event.release.tag_name}}-darwin-${{ matrix.arch }}.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.release.tag_name}}-darwin-${{ matrix.arch }}.tar.gz
          path: ${{github.event.release.tag_name}}-darwin-${{ matrix.arch }}.tar.gz

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["${{github.event.release.tag_name}}-darwin-${{ matrix.arch }}.tar.gz"]'
