on:
  release:
    types: [created]

env:
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: windows-2025
    strategy:
      matrix:
        arch: ['x64']
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: "24.x"

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps
        run: choco install nasm

      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Environment Information
        run: npx envinfo

      - name: Generate project files
        run: ./vcbuild.bat projgen

      - name: Build Qode binary
        run: node ./qode/build.js
        env:
          TARGET_ARCH: ${{ matrix.arch }}

      - name: List all output files
        run: ls -alp ./out/Release

      - name: Compress files
        uses: a7ul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          cwd: ./out/Release
          files: |
            ./qode.exe
            ./node.lib
          outPath: ${{github.event.release.tag_name}}-win32-${{ matrix.arch }}.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.release.tag_name}}-win32-${{ matrix.arch }}.tar.gz
          path: ${{github.event.release.tag_name}}-win32-${{ matrix.arch }}.tar.gz

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["${{github.event.release.tag_name}}-win32-${{ matrix.arch }}.tar.gz"]'